rtCamp/snapwp

.github/workflows/generate-schema.yml, packages/cli/package.json, packages/query/package.json
Updates our CI and npm package descriptions before v0.0.1 release
CI was previously configured against the private repository.
-   [x] I have read the [Contribution Guidelines](../CONTRIBUTING.md).
=> ci: prerelease cleanup

.github/workflows/publish.yml
-   [ ] I have read the [Contribution Guidelines](../CONTRIBUTING.md).
-   [ ] My code is tested to the best of my abilities.
-   [ ] I have updated the project documentation accordingly.
=> ci: enable publish to NPM

packages/cli/CHANGELOG.md
Adds the release notes for `snapwp@0.0.2` to "officially" release it.
Follows up #27 
Depending on the amount of feedback we get, might need take reprioritize changesets: https://github.com/rtCamp/headless/issues/389
=> release: `snapwp@0.0.2`

package-lock.json, packages/cli/CHANGELOG.md
Bump `package/cli` to v0.0.3
Because we dont have changesets.
=> chore: `snapwp` version bump to 0.0.03

package-lock.json, packages/cli/package.json
Follow up to #35 
because I Forgot to bump manually in `package.json`
-   [ ] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRIBUTING.md).
-   [ ] My code is tested to the best of my abilities.
-   [ ] I have updated the project documentation accordingly.
=> fix: bump package.json (packages/cli)

packages/next/README.md
Added ScriptModule and Fonts in documentation.
To understand use of it.
Part of : [#303](https://github.com/rtCamp/headless/issues/303)
next package is missing docs for some exports
=> docs: add `Fonts` and `ScriptModule` components to `snapwp/next` readme

docs/cors.md, docs/getting-started.md
- This PR adds the `cors.md` document to the `docs` directory, providing information on resolving CORS issues encountered on websites.
- If the CORS issue is not fixed, some functionalities may not work as expected.
- Closes: https://github.com/rtCamp/headless/issues/394
=> docs: add how-to for `Handling CORS Issues with Static Assets`

examples/nextjs/starter/codegen.ts, packages/codegen-config/src/index.ts
Optimizes GraphQL Codegen configurations for both packages and starter template with improved TypeScript integration and developer experience.
Current GraphQL Codegen configurations are basic and need optimization for specific use cases while maintaining good developer experience.
- Part of [#318](https://github.com/rtCamp/headless/issues/318)
- Added `useTypeImports: true` for better TypeScript integration
- Implemented `enumsAsTypes: true` for better type safety
- Set `maybeValue: 'T | null'` for explicit nullability
- Kept starter configuration minimal for better DX
- Avoided overly strict configurations that could impact developer experience
1. Clone the branch
2. Run `npm install`
3. Test in packages:
```bash
cd packages/query
npm run codegen
```
4. Test in starter:
```bash
cd …
```
=> chore: Optimize GraphQL Codegen config

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/codegen-config/CHANGELOG.md, packages/codegen-config/package.json, packages/next/CHANGELOG.md, packages/next/package.json, packages/query/CHANGELOG.md, packages/query/package.json
Updates readmes and bumps the version for the following packages:
- `snapwp`: 0.0.3 => 0.0.4
- `@snapwp/codegen-config`: 0.01 => 0.0.2
- `@snapwp/next`: 0.0.1 => 0.0.2
- `@snapwp/query`: 0.0.1 => 0.0.2
Because we're still releasing manually.
=> chore: version bump

package-lock.json, packages/cli/package.json, packages/codegen-config/package.json
Bumps the versions for `snapwp` and `@snapwp/codegen-config`
Because they werent rebuilt before being pushed.
Symptom of https://github.com/rtCamp/headless/issues/389
=> chore: rerelease deps for build

docs/config-api.md, docs/getting-started.md
- This PR will update the `config-api.md` to reflect the current implementation of config manager.
- We have made changes to the implementation of the config API, which will require the Documents to be changes so it can be used in a proper way.
- Closes: https://github.com/rtCamp/headless/issues/403
=> docs: update Config API doc

README.md
Fix broken documentation link in README.md by correcting the path to WordPress behavior documentation.
The current link in README.md points to a non-existent path (`overloading-wordpress-behaviour.md`), which needs to be updated to match the actual documentation file path (`overloading-wp-behavior.md`).
N/A
Updated the markdown link in README.md from:
`[Overloading WordPress Behavior](docs/overloading-wordpress-behaviour.md)`
to:
`[Overloading WordPress Behavior](docs/overloading-wp-behavior.md)`
1. Check out this branch
2. Open README.md
3. Click on the "Overloading WordPress Behavior" link
4. Verify it correctly leads to the documentation page
N/A
N/A
-   [x] My code …
=> docs: fix links in Overloading WP Behavior in `README.md`

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, DEVELOPMENT.md, README.md, docs/getting-started.md, docs/overloading-wp-behavior.md, examples/nextjs/starter/README.md, packages/blocks/README.md, packages/cli/README.md, packages/query/README.md
This PR cleans up various readme issues. More specifically,
- fixes misc typos
- adds the CLI package to the Directory Structure
- Updates the GH templates
- Adds Discord to the Issue template picker.
Pre-0.1.0 cleanup
=> docs: cleanup readmes

.changeset/ninety-yaks-laugh.md, .changeset/short-pens-refuse.md, .changeset/strange-kids-provide.md, .changeset/thick-days-heal.md, .changeset/twenty-needles-dress.md, .changeset/two-items-greet.md, .prettierignore
Backfills changesets for all the PRs merged to `develop` that arent currently on `main`.
=> chore: backfill changesets

examples/nextjs/starter/package-lock.json
Update `package-lock.json` in `examples/nextjs/starter` to maintain dependency consistency
Keep dependency versions in sync with latest updates in the Next.js starter template
N/A
Updated package-lock.json file to reflect current dependency versions
1. Navigate to examples/nextjs/starter
2. Run `npm install` to verify package installation works correctly
3. Start the development server to ensure no breaking changes
N/A
Regular maintenance update for dependency management
=> fix: Update `package-lock.json` in nextjs starter

docs/getting-started.md
This PR adds the Troubleshooting section to the Getting Started doc.
https://github.com/orgs/rtCamp/projects/141/views/14?pane=issue&itemId=98285209
Instructions to refer to the GitHub issues have been added.
=> docs: update Troubleshooting section in Getting Started

.changeset/long-chairs-press.md, packages/cli/README.md
This PR updates the readme for the CLI package to include general information about SnapWP overall, along with the usual footers.
It's not prefixed by the org, so it makes sense to surface it as an entrypoint to the monorepo.
=> chore: update CLI package readme

docs/getting-started.md
Adds documentation for manually using `@snapwp` libraries in a next js app.
=> Docs: add manual installation steps

.eslintrc.cjs, packages/core/src/config/tests/snapwp-config-manager.test.tsx, packages/core/src/logger/tests/logger.test.ts
- This PR implements [no-empty-function](https://eslint.org/docs/latest/rules/no-empty-function) preventing any empty functions increasing code readability.
-   [ ] I have added a changeset for this PR using `npm run …
=> feat: Add `no-empty-function` eslint rule

.changeset/spicy-worlds-wait.md, examples/nextjs/starter/README.md
Adds directory structure and key configuration file information to the Next.js starter readme.
The existing readme had a @todo section for directory structure and features. This PR completes that section with clear documentation to help new developers understand the project structure and key integration points.
- Part of rtCamp/SnapWP
- Added a concise directory structure showing the key files and folders
- Added brief descriptions for the most important configuration files
- Focused only on SnapWP-specific elements that new developers need to understand
- Kept comments minimal and relevant
1. Navigate to the `examples/nextjs/starter` directory
2. Review the updated README.md
3. Verify that the directory structure matches the actual project structure
4. Ensure the descriptions are …
=> docs: Add directory structure to `examples/nextjs/starter` readme

packages/cli/CHANGELOG.md
Run `npm run format`
Nobody else did it yet.
Workaround until https://github.com/rtCamp/snapwp/issues/121
-   [ ] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRIBUTING.md).
-   [ ] My code is tested to the best of my abilities.
=> chore: run `npm run format`

.github/workflows/release_packages.yml
Fixes a typo in git push command added in PR #127
The typo causes action to fail
- Resolves #121
- Part of #127
=> fix: typo in git push command

.changeset/curly-baths-send.md, packages/next/package.json
- This PR fixes the missing type definition error in the example.
- TypeScript couldn't find the type declaration for `withSnapWP` because it wasn't included in `package.json`.
- Closes: https://github.com/rtCamp/snapwp/issues/134
- Passed the type declaration for `withSnapWP` from `package.json`, ensuring that whenever `withSnapWP` is imported, the type declaration is also imported if required.
1. `cd examples/nextjs/starter`
2. Rename next.config.mjs => next.config.ts
3. add "noImplicitAny":  true and "checkJs":true to `tsconfig.json`
4. Execute `npm run typecheck`
-   [x] My code passes all lints (ESLint, tsc, …
=> fix: add with-snap-wp.d.ts as the types of the ./withSnapWP import

.changeset/rotten-mice-argue.md, examples/nextjs/starter/package.json, package-lock.json, package.json, packages/codegen-config/package.json, packages/core/package.json, packages/e2e-tests/package.json, packages/query/package.json
This PR updates NPM devDependencies to their latest versions, as well as the starter dependencies.
Ongoing maintainance.
- Part of https://github.com/rtCamp/headless/issues/416
See comments on diff.
=> chore: update NPM dev-dependencies

.changeset/hip-hats-remain.md, .eslintrc.cjs
-  Enforces no empty functions via ESLint.
- Improve code quality and prevent unintentional empty logic blocks.
- Part of [https://github.com/rtCamp/headless/issues/250](https://github.com/rtCamp/headless/issues/250)
- Enabled `@typescript-eslint/no-empty-function` and `no-empty-function` rules, with exceptions for test files.
-   [x] I have added a changeset for this PR …
=> chore: enforce `@typescript-eslint/no-empty-function`

DEVELOPMENT.md
Adds documentation for `--proxy` flag of `snapwp` command.
Updates the Setup section in `DEVELOPMENT.md` to have the following sub-sections - 
- Building SnapWP packages - Meant to provide steps on how to build all SnapWP packages and use them in the next app in the starter directory.
- Linking the CLI command - steps on how to link the command. Also has one optional step for scaffolding a project with proxied dependencies.
- Publish to local registry - step to start and publish on the proxy server.
https://github.com/rtCamp/headless/issues/453
-   [ ] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRIBUTING.md).
-   [ ] My code is tested to the best of my abilities.
-   [ ] …
=> chore: add doc for cli usage

.changeset/curvy-bees-camp.md, packages/plugin-apollo-client/src/engine/index.ts, packages/query/src/utils/query-generation.ts
- This PR will fix the issue with dynamic query generation.
- Currently we will add no-cache as fetchPolicy which will not try to search dynamically generated query from cache.
=> fix: add no-cache for apollo client to allow dynamic query generation
