rtCamp/snapwp

docs/getting-started.md
packages/cli/README.md
packages/cli/build.cjs
packages/cli/package.json
packages/cli/src/snapwp.cjs

- This PR 
- Updates `docs/getting-started.md` doc.
- Adds `packages/cli/README.md`.
- Adds the following files/folders to ignore list of SnapWP command:
- .env
- .next
- next-env.d.ts
- src/__generated
- Updates `fs.cpSync` function to `fs.cp` in SnapWP command.
- Removes `npm install` from SnapWP command adds user steps for the same.
- To fix SnapWP command and to add proper documentation.
- https://github.com/rtCamp/headless/issues/303
- Runs the `Development` from `packages/cli/README.md`.
-   [x] I have read the [Contribution Guidelines](../CONTRIBUTING.md).
-   [ ] I have added unit tests to verify the code works as …

fix: remove internal `npm install` call from `npx snapwp` command

---

packages/cli/package.json
packages/cli/src/snapwp.cjs

- This PR updates the regex for snapwp command.
- https://github.com/rtCamp/headless/issues/303
- Run the `Development` from `packages/cli/README.md`.
- The previous regex was matching the node_modules path:
i.e. if our scaffold path is
`/Users/amaankhan/.nvm/versions/node/v20.10.0/lib/node_modules/snapwp/dist/examples/nextjs/starter/`
then our previous regex i.e. `/.*(node_modules|package-lock\.json|\.env|\.next|next-env\.d\.ts|src\/__generated)/g` will always return true.
-   [x] I have added unit …

fix: update regex in `snapwp` command to avoid `node_modules`

---

.github/workflows/pull_request_examples.yml

Changes from using a private token to the one generated in workflow as `snapwp-helper` is now public for checking out this repo in example build.
Previously we were using an internal token for checking out the repo, but now since it is public and we need forks running this workflow to be able to run the action, we change it to use the token from workflow itself.
-   [ ] I have updated the project documentation accordingly.

ci: update examples workflow to use generated token

---

docs/getting-started.md

This PR fixes several formatting/styling issues in `getting-started.md`
- Fixed the formatting for the Backend Setup Installation Steps, and removed the comment to make the wp-cli command copy-pasteable.
- Clarified the internal link for the backend prerequisites.
- Fixed the image alignment in `Create an Environment File`.
Addresses QA + external feedback.
- Part of https://github.com/rtCamp/headless/issues/395
- Part of https://github.com/rtCamp/headless/issues/353
-   [x] I have added unit tests to …

docs: cleanup `Getting Started` instructions

---

packages/cli/src/snapwp.cjs

- This PR will:
- Fix fs.cp (copy) functionality in snapwp command by migrating `fs` to `fs/promises`.
- Move the `.env` file generation from step 3 to step 2 in our command.
- Remove emojis as they are not supported on Windows terminal.
- https://github.com/orgs/rtCamp/projects/141/views/14?pane=issue&itemId=96437176
- Run the Development from `packages/cli/README.md`.

fix: Migrate fs to fsPromises in snapwp command

---

docs/overloading-wp-behavior.md
packages/query/src/fragments/core-template-part.graphql

This PR enhances the overloading capabilities for template parts in SnapWP.
This PR ensures overloading of Template-parts by introducing attributes such as `classname`, `slug` and `theme`. This PR also updates the `docs/overloading-wp-behavior` to add a section on how to overload a template part.
Previously, only `templatePartTagName` was available, limiting the ability to precisely target and overload template parts.
By including `slug`, `className`, and `theme`, users can now target specific template parts more granularly, enabling greater customization.
The new docs provide clear guidance on how to implement overloading using these attributes.
- Part of [Task: Ensure that Block Patterns, Template Parts, and Templates are overloadable](https://github.com/rtCamp/headless/issues/398)
- …

chore: Ensure `CoreTemplatePart` blocks are overloadable

---

examples/nextjs/starter/snapwp.config.mjs
examples/nextjs/starter/snapwp.config.ts
packages/blocks/jest.setup.js
packages/core/jest.setup.js
packages/core/src/config/snapwp-config-manager.ts
packages/core/src/config/tests/snapwp-config-manager.test.ts
packages/next/src/config/with-snap-wp.ts

This PR separates the config variables into two types:  
1. **EnvConfigs**  
2. **SnapWPConfigs**  
The key difference between these two is that **EnvConfigs** will contain all the configurations declared inside the `.env` file, which will be available during the Next.js build routine. In contrast, **SnapWPConfigs** will include configurations to override block definitions, queries, etc., and will only be available at runtime in Next.js.  
Additionally, this update introduces generic types to improve the type definitions for configurations.
With this change, we will support the TypeScript config file along with all other possible overrides provided through our config file.
- Part of https://github.com/rtCamp/headless/issues/403
-   [x] I have read the [Contribution …

feat: add support for snapwp.config.ts

---

DEVELOPMENT.md

Add missing `.env` setup step to development documentation to ensure proper environment configuration.
Currently, the development setup documentation doesn't include the crucial step of copying `.env.example` to `.env`. This can lead to confusion and setup issues for new contributors since various build and development processes may depend on environment variables.
Fixes a [draft issue](https://github.com/orgs/rtCamp/projects/141/views/14?pane=issue&itemId=97131680)
- Added a new step at the beginning of the setup instructions in `DEVELOPMENT.md`
- Included the command `cp .env.example .env` with proper formatting
- Reordered existing steps to ensure environment setup occurs before other installation steps
1. Clone the repository fresh
2. Follow the updated setup instructions in …

docs: add copy `.env.example` to DEVELOPMENT.md setup steps

---

config/tsconfig.base.json

This PR makes the following changes to `tsconfig.base.json`. Reasons are included alongside the change:
- `noImplicitOverride: true` - We're using classes, and we may want to extend them in future packages
- `declaration: true` - We're a library. `d.ts` files help end user IDEs
- `sourceMap: true` -  We're a library, sourcemaps help end users debug
- `isolatedModules:  true` - limits some ts edge cases.
- `moduleDetection: "force"` - Prevents unexpected behavior leaking from autodetection.
- `resolveJsonModule: true` - so we can import .json
- `module|target: es2022` - the modern "stable" version.
These are all noncontroversial, incremental improvements that don't require any existing code changes to satisfy.
Individual property explanations are here …

chore: implement additional tsconfig properties

---

packages/blocks/src/blocks/core-media-text.tsx
packages/core/src/config/snapwp-config-manager.ts
packages/core/src/config/tests/snapwp-config-manager.test.ts
packages/next/src/components/image.tsx
packages/next/src/components/link.tsx
packages/next/src/middleware/cors.ts
packages/next/src/middleware/current-path.ts
packages/next/src/middleware/proxies.ts
packages/next/src/middleware/utils.ts
packages/next/src/root-layout/index.tsx
packages/query/src/query-engine/index.ts
packages/query/src/utils/parse-global-styles.ts
packages/query/src/utils/parse-template.ts

This PR updates usages of typescript types to explictly import using the `type` syntax, as mandated by TSConfig's `verbatimModuleSyntax`
Cherrypicked from #65 to avoid collecting tech debt while we wait for the jest tests to be fixed and the tsconfig file to be updated.
Part of: https://github.com/rtCamp/headless/issues/317

chore: use explicit type imports

---

DEVELOPMENT.md

Improve setup instructions to clarify build prerequisites for development mode
The current setup instructions don't clearly indicate that `npm run dev` requires either a build step or local package publishing to work properly. This can lead to confusion and setup failures for new developers.
- Restructured setup instructions to show two clear paths:
1. Build + Dev mode
2. Local publishing
- Removed ambiguous "alternatively" phrasing
- Added explicit grouping of related commands
- Maintained all existing setup steps while improving clarity
1. Clone the repository
2. Follow new setup instructions using either path:
**Path A:**
```bash
npm install
npm run build
npm run dev
```
**Path B:**
```bash
npm install
npm run publish:local
```
3. Verify development environment starts successfully
This …

docs: clarify `npm run dev`

---

config/tsconfig.base.json
packages/blocks/src/block-manager/index.tsx
packages/blocks/src/blocks/core-image.tsx
packages/core/src/utils/get-style-object-from-string.ts
packages/next/src/components/image.tsx
packages/next/src/components/link.tsx

This PR enables [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess) and attempts to remediate the exposed smells
Part of https://github.com/rtCamp/headless/issues/317
See the commit history. Each remediation occurs in its own commit.

dev: enable `noUncheckedIndexedAccess` and remediate exposed issues

---

.changeset/nice-bears-notice.md
packages/core/src/config/snapwp-config-manager.ts
packages/core/src/config/tests/snapwp-config-manager.test.ts
packages/core/src/utils/replace-host-url.ts

This PR fixes the bug where links would break when there is no trailing slash in `NEXT_PUBLIC_URL` or `NEXT_PUBLIC_WORDPRESS_URL`
Links would not work.
`normalizeConfig` is updated to remove trailing slashes from `homeUrl` and `nextUrl`.

fix: links breaking when there is no trailing slash in `NEXT_PUBLIC_URL`

---

.changeset/loud-carrots-repair.md
.eslintrc.cjs
packages/eslint-config/index.js

This PR removes the Eslint config `overrides` from `@snapwp/eslint-config` and relocates them into our own package.
We want our package to implement smart and measured rules that make sense contextually, but these leaked into the initial release. 
They may even be restored as a ruleset.
- Cherrypicked from https://github.com/rtCamp/snapwp/pull/84
- Part of https://github.com/rtCamp/headless/issues/250
This is a breaking change as those relying on those previous overrides will now need to override them themselves.
-   [x] My code has detailed inline …

refactor!: move ESLint overrides from package to local ruleset

---

.changeset/poor-lands-study.md
packages/next/README.md
packages/next/src/components/script-module.tsx

This PR adds compatibility for `ScriptModuleDependency.importType` now returning an enum instead of a string.
Compatibility with https://github.com/rtCamp/snapwp-helper/pull/88
`toUpperCase()` coersion is used for backwards-compatibility. This will be stripped for our next breaking release (when we drop support for the snapwp-helper v0.1.0
I didn't bother narrowing down the types. it feels like there's gonna be a lot of type changes and no need to bump them now unnecessarily, imo.
-   [x] I have added …

dev: add compat for ScriptModuleImportTypeEnum

---

.changeset/loud-carrots-repair.md
.eslintrc.cjs
package-lock.json
package.json
packages/eslint-config/index.js
packages/eslint-config/package.json

- This PR reformats eslint rulesets i.e. migrate configurations to their respective places & adds following plugins + rulesets:
- `@typescript-eslint/parser` parser migrated from `packages/eslint-config/index.js` as it is not required in public package because JavaScript files are shipped. (ref: https://github.com/rtCamp/snapwp/pull/60#issuecomment-2654116722)
- ignorePatterns are sorted ascending.
- Restricts use of `classnames` & `lodash` imports in TypeScript files.
- If a default import is requested, this rule will report if there is no default export in the imported module.
- Verifies that all named imports are part of the set of named exports in the referenced module.
- There can be test cases that might not have expect call made.
- Allows adding type-definitions to `@param` & …

chore: cleanup ESLint rulesets

---

.eslintrc.cjs
packages/next/src/root-layout/index.tsx

- This PR implements [react/jsx-boolean-value](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) forcing to omit the true value passed to JSX component's prop to maintain consistency in code. (JFI: if a prop requires a boolean value & if no value is passed, by default it is true [[Ref](https://www.freecodecamp.org/news/react-props-cheatsheet/#:~:text=React%20props%20passed%20with%20just%20their%20name%20have%20a%20value%20of%20true)])
-   [x] My code is tested to the …

chore: Add `react/jsx-boolean-value` eslint rule to codebase

---

.changeset/fluffy-crabs-rhyme.md
packages/core/src/props/index.ts
packages/next/README.md
packages/next/src/components/script.tsx
packages/next/src/template-renderer/template-scripts.tsx
packages/query/src/queries/get-current-template.graphql

Change `location` property to `groupLocation` with proper enum type to match backend GraphQL schema updates
This PR updates the frontend code to be compatible with the backend changes that switched from using `location: String` to `groupLocation: ScriptLoadingGroupLocationEnum`
- Part of: rtCamp/snapwp
- Created a `ScriptLoadingGroupLocationEnum` type with 'HEADER' and 'FOOTER' values
- Updated prop interfaces to use `groupLocation` instead of `location`
- Updated component logic to use the new enum values
- Modified GraphQL query to fetch `groupLocation` instead of `location`
- Updated documentation to reflect the new property name
1. Add a script with `groupLocation="HEADER"` in a component
2. Verify script loads in the header with 'beforeInteractive' strategy
3. Add a script with …

refactor!: Change `location` to `groupLocation` for script placement enum type

---

.eslintrc.cjs
packages/next/src/root-layout/global-head.tsx

- This PR will add [react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) rule preventing unnecessary JSX curly braces when literals alone are enough.
-   [x] I have updated the project …

chore: Add `react/jsx-curly-brace-presence` eslint rule

---

.changeset/fair-carrots-invite.md
packages/next/src/config/with-snap-wp.ts

Allows users to add to remote patterns.
- Fixes #110 
N/A
N/A

fix: allow remotePatterns to be overridden

---

.eslintrc.cjs
packages/blocks/src/editor-blocks-renderer/index.tsx
packages/core/src/logger/index.ts
packages/next/src/config/with-snap-wp.ts
packages/next/src/middleware/cors.ts
packages/types/src/blocks/base.ts
packages/types/src/blocks/definitions.ts
packages/types/src/blocks/props/core-video.ts

- This PR add [@typescript-eslint/no-explicit-any](https://typescript-eslint.io/rules/no-explicit-any/) eslint rule.

dev: Add `@typescript-eslint/no-explicit-any` eslint rule

---

.changeset/shy-planets-hunt.md
.eslintrc.cjs
packages/cli/src/snapwp.cjs

- This PR 
- Enables use of console and process-env in CLI and bin files + fixes their eslint errors. 
- Removes unused `exec` function from CLI package.
-   [ ] I have added a changeset for this PR using `npm run …

chore: Apply and enforce ESLint rules to `bin` and `cli` files

---

.changeset/empty-pigs-fry.md
packages/next/src/components/default-error.tsx
packages/next/src/template-renderer/index.tsx

This PR displays an error when `editorBlocks` are not defined.
Currently, no message is displayed when editorBlocks is undefined.
https://github.com/orgs/rtCamp/projects/141/views/10?pane=issue&itemId=99060513
The `DefaultError` component is used to display this message: 'Error: Unable to render content. `editorBlocks` is not defined. This may be due to missing template data or an issue with data fetching.'
-   [ ] I have updated the …

feat: Display error fallback when no editor blocks

---

.github/workflows/release_packages.yml

Runs a prettier format check on changesets PR to reformat anything which doesn't align with `format:check` using the `format` script.
Sometimes the changesets pull request is not properly formatted. This is to fix that.
Refer #121 for more details.
- Resolves #121
1. Changeset pull request creation logic runs as is
2. We run `npm run format` on the pull request itself
3. If any file is changed, we commit, and then push to PR.
4. If there are no files which changed, everything is properly formatted.
This fix relies on relation between `format` and `format:check` scripts. If `format` is not properly validated by `format:check`, this fix may fail.
-   [x] My code is …

ci: prettier format on changesets pr

---

.changeset/cold-cows-joke.md
examples/nextjs/starter/codegen.ts
packages/core/src/config/snapwp-config-manager.ts
packages/query/codegen.ts

This PR uses `SITE_URL` for GraphQL endpoint instead of `HOME_URL`
In a bedrock setup, the graphql server is at host:port/wp/graphql and host:port/wp is the WP SITE_URL whereas often the HOME_URL will be just host:port
https://github.com/rtCamp/snapwp/issues/149
Updated instances of generateGraphQLUrl() - passed SITE_URL instead of HOME_URL, per [WPGraphQL’s logic](https://github.com/wp-graphql/wp-graphql/blob/200dcef15f98fecc0af3d3852bdb9792488dfa8d/access-functions.php#L874).
-   [x] I have added unit …

fix: use `SITE_URL` for GraphQL endpoint instead of `HOME_URL`

---

.changeset/tall-pens-rule.md
packages/next/src/middleware/proxies.ts
packages/next/src/root-layout/icons-metadata.ts

- This PR will fix the new GraphQL request sent for favicon.ico
- When icon tag is not available in head tag browser tries to fetch it from /favicon.ico path. This request is getting to the NextJS Server and it is considering this request to a page request and making a GQL request to fetch favicon.ico request.
- Passing # as icon when Icon is not available
-   [x] I have …

fix: avoid unnecessary `favicon.ico` requests when unset

---

.github/workflows/pull_request_examples.yml

This pull request updates the `.github/workflows/pull_request_examples.yml` file to simplify the handling of temporary directories for test apps by directly using `${{ runner.temp }}/snapwp-test-app` instead of relying on the `TEST_APP_DIR`  (which when defined, does not have `runner` context) environment variable. This change ensures consistency and reduces the need for an additional variable.
* Removed the `TEST_APP_DIR` environment variable and replaced its usage with `${{ runner.temp }}/snapwp-test-app` throughout the workflow. This affects directory creation, working directories, and cleanup steps.

fix: update test app directory path to use runner.temp

---

.changeset/orange-worms-shout.md
examples/nextjs/starter/package.json

This PR resolves a conflict caused by eslint-plugin-react-hooks being pulled in by both:
eslint-config-next
@wordpress/eslint-plugin
ESLint does not allow multiple versions of the same plugin in a single config, resulting in a plugin conflict error when running eslint.
By adding the overrides field in the test app, we force a single version (^5.2.0) of eslint-plugin-react-hooks to be used throughout the dependency tree
Added a package-level overrides entry in the test app's package.json:
```json
"overrides": {
"eslint-plugin-react-hooks": "^5.2.0"
}
```
1. Run `snapwp`
2. Scaffold the test app outside the snapwp directory, e.g. `../snapwp-app`
3. Run `npm run lint` in `snapwp-app`
-   [x] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRI …

fix: override `eslint-react-hooks-plugin`

---

.github/workflows/pull_request_examples.yml

Change the use of `npm link` in ci with a temporary local install.
CLI version used after `npm link` is still the one from npm registry, and not the one built locally.
- https://github.com/rtCamp/headless/issues/460
Replaced use of `npm link` in ci with a local install for locally built CLI version and then use it via `npx` to avoid using global version of SnapWP CLI. During internal testing, this turned out to be less error prone, whereas for `npm link`, it would sometimes use local version and sometimes one from npm registry, and show different errors randomly.
-   [x] My code passes all lints (ESLint, tsc, …

fix(ci): use locally built version of snapwp starter template

---

.changeset/gentle-places-strive.md
packages/query/src/fragments/blocks/core-cover.graphql
packages/query/src/fragments/blocks/core-image.graphql
packages/query/src/fragments/blocks/core-media-text.graphql
packages/query/src/fragments/seo/template/route-metadata.graphql
packages/query/src/queries/get-current-template.graphql

Adds missing `id` fields to GraphQL node fragments
Global IDs are used both server and client side for efficient caching
Part of https://github.com/rtCamp/headless/issues/428

dev: add `id` to GraphQL node fragments

---

.changeset/witty-maps-chew.md
.eslintrc.cjs
packages/eslint-config/index.js

This PR adds `@typeParam` to the `jsdoc/check-tag-names` allowlist, and then enforces that rule as an `error` on our internal repo.
Eslint warnings should still be resolved.
`npm run lint`
Before/ after:

fix: add TSDoc `@typeParam` to `jsdoc/check-tag-names` allowlist

---

.github/workflows/publish.yml

The release action fails when attempting to publish a 'private' package.
In case of a package marked as `private` through `package.json`, the package is not published to NPM, but a github release is created. When the same package with the same version number is encountered twice, the github release creation fails.
Specifically for packages marked with `"private": true`, we go ahead and check if a github release exists or not. If it does, then we skip creating one, otherwise we always create one.
-   [ ] …

Fix/private packages GitHub release
